---
title: "Resume"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

1. **빠른 실행력은 최고의 경쟁력, 업무 방식**

DONE is better than perfect. 

일단 실행하고 완벽에 가깝게 개선하는 스타일입니다. 

세상에는 풀지 못한 여러가지 문제들이 있습니다. 

이 문제들을 풀 아이디어는 여럿 등장하고 있지만 그 아이디어를 ‘실현’할 수 있는 사람은 여럿 없습니다. 

실행에 옮기고 사용자의 경험을 통한 여러 테스트를 통해 빠른 피드백을 이루어내는 것이 저의 사업적 목표입니다. 

실행에 옮기기 위한 [기술](https://www.notion.so/325fd7e6979a479885013ca86659f9e7)을 내가 가지고 있다는 것, 그 기술을 활용해 빠르게 실행으로 옮길 수 있는 열정이 제가 가진 경쟁력이며, 나다운 것 중 하나입니다.

2. **기억보다 기록을, 인생을 한권의 책으로**

간접적인 배움의 방식 중 독서와 강의는 그냥 흘려보내지 않습니다. 

한번 보고 기억할 수 없기에 볼 때마다 요약, 정리합니다. 

그리고 다시 봅니다. notion을 통해 모바일에서나 pc에서나 시간이 날때마다 복습할 수 있습니다. 

이러한 모바일 유틸리티를 적극적으로 활용하는 것도 배움의 중요한 방식입니다

📚[독서 일지 Blog](https://www.notion.so/a3524d14db9a44c58d1c2dbeecf5a2fe) 🖥️[강의 노트 Blog](https://www.notion.so/5db66330df334da9802f507083e44a05)


## Skills

**상상을 현실로 만드는 _ 디자인**

- Adobe illustrator CC 2022(上), photoshop CC 2021 (上), 
- Adobe XD CC 2021, Figma (上), 
- Adobe Premiere Pro CC 2022(中), After Effect CC 2021(中)


**클릭을 부르는 한 문장, 카피라이팅**

홍보, 디지털 마케팅 분야에서의 카피라이팅 경험

광고 카피, 칼럼 카피 등 글쓰기 경험

- 페이스북, 인스타그램 게시물 광고: 5,000명의 클릭, 200명 이상의 전환
- 강의 노트, 독서 일지 Blog, 글 40건 이상
- 에브리타임을 통한 동아리 모집 홍보글 연간 30개 작성


**하나 같은 여럿 _ 협업 툴**
- Slack, Notion
- Upsource
- Google WorkSpace, Drive(Form, members)
- Ms Office (PowerPoint, Excel, Word, Teams), Flow


**어학 **

- 오픽 AL
- 토익 990점


**SW 스킬 **

노코드 툴(버블, 자피어) 기반 웹서비스 개발

## Work Experience & Career

**DSM (대학생 선교 동아리) 활동 **

한양대 DSM 회장(20.07~21.08)

서울지부 DSM  학생 대표(22.03~22.12)

DSM 활동이 사랑, 정직, 겸손, 섬김을 배우는 시간이었음.


**코람데오 창업 및 대표 (21.09~22.1) **

메타버스 기반 화상 관리형 독서실, 메타 클래스 창업

고객 20명, 월 매출 200만원 달성


## Award experience
생애최초 청년 창업지원 사업 최종 선정

HY 캠퍼스타운 지원사업 선정

경영대학 창업경진대회(lions competition) 최우수상 수상

한양대학교 창업경진대회 우수상 수상



